declare namespace NodeJS {
	interface ProcessEnv {
		NEXT_PUBLIC_APP_TITLE: string;
		NEXT_PUBLIC_APP_DESCRIPTION: string;
		NEXT_PUBLIC_APP_INSTAGRAM: string;
		NEXT_PUBLIC_APP_YOUTUBE: string;
		NEXT_PUBLIC_APP_APARAT: string;
		NEXT_PUBLIC_APP_GOOGLEPLAY: string;
		NEXT_PUBLIC_APP_APPSTORE: string;
		NEXT_PUBLIC_APP_MOBILE_NUMBER: string;
		NEXT_PUBLIC_APP_TELEPHONE_NUMBER: string;
		NEXT_PUBLIC_BACKEND_STORAGE: string;
		NEXT_PUBLIC_BACKEND_API_URL: string;
		NEXT_PUBLIC_FRONT: string;
	}
}
